"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def Fibonnacci(a,b):
    value = 0
    sum = 0
    if (a%2 ==0):
            sum += a
    if (b%2 ==0):
            sum += b
    
    while value <= 4000000:
        value = a + b
        a = b
        b = value
        if (value%2 ==0):
            sum += value
    return sum

print(Fibonnacci(1,2))


